config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  root 'jobs#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :catergory
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :find_job, only: [:show, :edit, :destroy, :update]
  def index
    if params[:category].blank?
			@jobs = Job.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@jobs = Job.where(category_id: @category_id).order("created_at DESC")
		end
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to @job
    else
      render "new"
    end
  end

  def edit
  end

  def show
  end

  def update
    if @job.update(job_params)
      redirect_to @job
    else
      render "edit"
    end
  end

  def destroy
    @job.destroy
    redirect_to root_path
  end

  private

  def find_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:title, :description, :url, :company, :category_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= simple_form_for @job do |f|
  = f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a category" }, input_html: { class: "dropdown-toggle" }
	
  =f.input :title, label: "Job Title", class: 'form-control'
  =f.input :description, label: "Job Description", class: 'form-control'
  =f.input :company
  =f.input :url
  =f.button :submit

app/views/jobs/edit.html.haml
%h2 Edit page
=render "form"

=link_to "Cancel", root_path, class: "btn btn-primary"

app/views/jobs/index.html.haml
#jobs
  -@jobs.each do |job|
    .job
      %h2= link_to job.title, job
      %p= job.description
      %p= job.company
      
=link_to "New Job", new_job_path, class: "btn btn-danger"

app/views/jobs/new.html.haml
%h2 new form
=render "form"
=link_to "Cancel", root_path

app/views/jobs/show.html.haml
%h2=@job.title
%p=@job.description
%p=@job.company
%p=link_to "Go To Job", @job.url
=link_to "Home", root_path, class: "btn btn-primary"
=link_to "Edit", edit_job_path(@job), class: "btn btn-primary"
=link_to "Delete", job_path, method: :destroy, class: "btn btn-primary"

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Rails Jobs App
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  %nav.navbar-default
    .container
      .navbar-brand Rails Jobs
      %ul.nav.navbar-nav
        %li=link_to "All Jobs", root_path
        -Category.all.each do |category|
          %li=link_to category.name, jobs_path(category: category.name)
      =link_to "New Job", new_job_path, class: "navbar-text navbar-right navbar-link"

  .container
    = yield